# Part 02 머신러닝을 위한 파이썬 패키지 - Chapter 03 넘파이

## 03 넘파이 배열 객체 다루기

### 2 배열의 메모리 구조

In [1]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [2]:
type(test_array[3])

numpy.float64

### 3 배열의 생성

In [4]:
test_array = np.array([1, 4, 5, "8"], float)
print(test_array)

[1. 4. 5. 8.]


In [5]:
print(type(test_array[3]))     # 실수형(floating Type)으로 자동 형 변환 실시

<class 'numpy.float64'>


In [6]:
print(test_array.dtype)     # 배열 전체의 데이터 타입 변환

float64


In [7]:
print(test_array.shape)     # 배열의 구조(shape)를 반환함

(4,)


#### 3.1 배열의 구조(shape)

In [8]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [9]:
tensor_rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [10]:
tensor_rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor_rank3, int).ndim

3

In [11]:
np.array(tensor_rank3, int).size

48

#### 3.2 dtype

In [12]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype = int)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype = float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [14]:
import sys
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype = np.float64).itemsize

8

In [15]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype = np.float32).itemsize

4

### 4 배열의 구조 다루기

In [16]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [17]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [18]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
x.reshape(2, 2)

ValueError: ignored